.mode columns
.headers on

DROP TABLE IF EXISTS POOL;
DROP TABLE IF EXISTS COACH;
DROP TABLE IF EXISTS SWIMMER;
DROP TABLE IF EXISTS CONTEST;
DROP TABLE IF EXISTS PARTIAL;

CREATE TABLE POOL (
  ID INTEGER PRIMARY KEY,
  NAME TEXT UNIQUE
);

CREATE TABLE COACH (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USERNAME TEXT NOT NULL UNIQUE,
  PASSWORD TEXT NOT NULL,
  NAME TEXT NOT NULL,
  POOL_ID INTEGER NOT NULL REFERENCES POOL,
  POOLMASTER INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE SWIMMER (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT,
  DOB TEXT NOT NULL,
  COACH_ID INTEGER TREINADOR,
  POOL_ID INTEGER REFERENCES POOL,
  PROFIL_PIC TEXT,
  UNIQUE(NAME, DOB, COACH_ID)
);

CREATE TABLE CONTEST (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  STYLE TEXT NOT NULL,
  POOLLENGTH INTEGER DEFAULT 25 NOT NULL CHECK(POOLLENGTH = 25 OR POOLLENGTH = 50),
  DAYOFCONTEST TEXT NOT NULL,
  SWIMER_ID INTEGER NOT NULL REFERENCES SWIMMER
);

CREATE TABLE PARTIAL (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CONTEST_ID INTEGER NOT NULL REFERENCES CONTEST,
  PARTIAL_TIME REAL NOT NULL CHECK(PARTIAL_TIME > 0)
);
